; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32, xiao-c6, ttgo, m5stick-c, m5stick-c-plus, m5stick_s3, m5stack-core2, m5stack-core-ink, e32r28t, c6-lcd, wokwi

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.17.3
    paulstoffregen/Time@^1.6.0
    jfturcot/SimpleTimer

[env:esp32]
platform = espressif32@6.9.0
board = esp32dev

lib_deps = 
    ${env.lib_deps}
    lovyan03/LovyanGFX

build_flags =
  -Os
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DINVERT=true
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=12
  -DTFT_RST=-1
  -DTFT_BL=2
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_RGB_ORDER=TFT_BGR
  -DSPI_FREQUENCY=27000000
  -DCDS=39
  -DCDS_THRESHOLD=90
  -DBTN=0

[env:xiao-c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
lib_deps = 
    ${env.lib_deps}
    lovyan03/LovyanGFX

build_flags =
  -Os
  -DXIAO_C6
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DINVERT=true
  ; -----------------------------
  -DTFT_MOSI=22    ; D4 (SDA)
  -DTFT_SCLK=23    ; D5 (SCL)
  -DTFT_DC=16      ; D6
  -DTFT_CS=1       ; D1
  -DTFT_BL=2       ; D2
  -DTFT_RST=-1     ; 抵抗プルアップ
  -DCDS=0          ; D0
  -DCDS_THRESHOLD=90
  -DBTN=19         ; D8
  -DTFT_MISO=-1
  -DMY_SPI_HOST=SPI2_HOST
  ; -----------------------------
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_RGB_ORDER=TFT_BGR
  -DSPI_FREQUENCY=27000000
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:ttgo]
platform = espressif32@6.9.0
board = esp32dev
lib_deps = 
    ${env.lib_deps}
    lovyan03/LovyanGFX

build_flags =
  -DTTGO
  -DTFT_BL=4
  -DINVERT=true
  -DMY_SPI_HOST=VSPI_HOST
  -DSPI_FREQUENCY=4000000
  -DTFT_SCLK=18
  -DTFT_MOSI=19
  -DTFT_MISO=-1
  -DTFT_DC=16
  
[env:m5stick-c]
platform = espressif32@6.9.0
board = m5stick-c
lib_deps = 
    ${env.lib_deps}
    m5stack/M5Unified

[env:m5stick-c-plus]
platform = espressif32@6.9.0
board = m5stick-c
lib_deps = 
    ${env.lib_deps}
    m5stack/M5Unified

build_flags =
  -DARDUINO_M5Stick_C_Plus

[env:m5stick_s3]
 platform = espressif32@6.9.0
 board = esp32-s3-devkitc-1
 board_build.arduino.memory_type = qio_opi
 board_build.arduino.partitions = default_8MB.csv
 build_flags = 
    -D ARDUINO_M5STICK_S3
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1        ; required
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ${env.lib_deps}
    m5stack/M5Unified

[env:m5stack-core2]
platform = espressif32@6.9.0
board = m5stack-core2
lib_deps = 
    ${env.lib_deps}
    m5stack/M5Unified

[env:m5stack-core-s3]
platform = espressif32
; Board definition for Core S3 (esp32s3box might be used depending on the environment)
board = m5stack-cores3
board_build.mcu = esp32s3

; Upload speed and serial monitor baud rate
upload_speed = 1500000
monitor_speed = 115200

; [CRITICAL] USB serial communication settings specific to ESP32-S3
build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_M5STACK_CORE_S3

; Specify the same libraries used for Core2
lib_deps =
  ${env.lib_deps}
  m5stack/M5Unified

[env:m5stack-core-ink]
platform = espressif32@6.9.0
board = m5stack-coreink
monitor_speed = 115200
upload_speed = 2000000
build_flags = 
  -D E_INK
lib_deps =
    ${env.lib_deps}
    m5stack/M5Unified

[env:e32r28t]
platform = espressif32@6.9.0
board = esp32dev
lib_deps =
    ${env.lib_deps}
    lovyan03/LovyanGFX @ ^1.1.12

build_flags =
  -DR28T
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DINVERT=false
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_BL=21
  -DTFT_RST=-1
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_RGB_ORDER=TFT_BGR
  -DSPI_FREQUENCY=27000000
  -DHOLD_BTN_TO_POWEROFF
  -DBTN=0

board_build.partitions = huge_app.csv


[env:c6-lcd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-c6-devkitc-1
lib_deps = 
    ${env.lib_deps}
    lovyan03/LovyanGFX

build_flags = 
    -D ESPC6
    -D SPOTPEAR_C6
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DTFT_BL=22
    -DBRIGHTNESS=99
    -DINVERT=true
    -DMY_SPI_HOST=SPI2_HOST
    -DSPI_FREQUENCY=4000000
    -DTFT_SCLK=7
    -DTFT_MOSI=6
    -DTFT_MISO=-1
    -DTFT_DC=15
  
[env:wokwi]
platform = espressif32@6.9.0
board = esp32dev
build_flags = 
  -D WOKWI
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_CS=15
  -DTFT_BL=33
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_RGB_ORDER=TFT_BGR
  -DSPI_FREQUENCY=4000000
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_MISO=19
  -DTFT_DC=2
  -DTFT_RST=4
  -D LGFX_USE_SPI=1
  -DINVERT=false
  -DMY_SPI_HOST=VSPI_HOST

lib_deps = 
  bblanchon/ArduinoJson@^6.17.3
  paulstoffregen/Time@^1.6.0
  lovyan03/LovyanGFX
